main: de.raidcraft.rcwarn.RCWarnPlugin
name: RCWarn
version: ${project.version}#${build.number}
description: Warn and ban system
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API RCMultiWorld]